import Head from 'next/head'
import { Banner, Header, Categories, Footer } from '../components'

export default function Home() {
  return (
    <>
      <Head>
        <title>Green Market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <Header />
        <Banner />
        <Categories />
        <Footer />

      </main>
    </>
  )
}
